<?php

namespace Message\Cog\Filter;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

/**
 * Class FilterForm
 * @package Message\Cog\Filter
 *
 * @author  Thomas Marchant <thomas@mothership.ec>
 *
 * Class representing the filter form that will be generated by the FormBuilder
 */
class FilterForm extends AbstractType
{
	/**
	 * @var string
	 */
	private $_name;

	/**
	 * @var FilterCollection
	 */
	private $_filters;

	/**
	 * Set the name of the form upon instanciation
	 *
	 * @param $name string
	 */
	public function __construct($name, FilterCollection $filters)
	{
		if (!is_string($name)) {
			throw new \InvalidArgumentException('Name must be a string');
		}

		$this->_name    = $name;
		$this->_filters = $filters;
	}

	/**
	 * {@inheritDoc}
	 */
	public function getName()
	{
		return $this->_name;
	}

	/**
	 * {@inheritDoc}
	 *
	 * Loop through filters and add form fields to main parent form
	 */
	public function buildForm(FormBuilderInterface $builder, array $options)
	{
		foreach ($this->_filters as $filter) {
			$builder->add(
				$filter->getName(),
				$filter->getForm(),
				$filter->getOptions()
			);
		}
	}
}